name: PR Command

on:
  pull_request_review_comment:
    types: [created]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Label PR
        uses: actions/github-script@v6
        with:
          script: |
            const command = context.payload.comment.body;
            if (command.startsWith('/label')) {
              const label = command.split(' ')[1];
              console.log(`Adding label ${label} to PR ${context.payload.pull_request.number}`);
              github.rest.issues.addLabels({
                issue_number: context.payload.pull_request.number,
                labels: [label]
              });
            }
