name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"

    - name: Create some mock artifacts
      run: echo "yeahh" >> test.tar.gz

    - name: Remove the previous weekly release.
      uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
        delete_release: true
        tag_name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release the artifacts
      uses: softprops/action-gh-release@v1
      with:
        files: |
          test.tar.gz
        name: Release @ ${{ steps.date.outputs.date }}
        tag_name: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
